server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;

    # 1. Redirigir la raíz exacta "/" a "/es-MX/"
    location = / {
        return 301 /es-MX/;
    }

    # 2. Manejar la aplicación en la carpeta es-MX
    location /es-MX/ {
        try_files $uri $uri/ /es-MX/index.html;
    }

    # 3. Redirigir cualquier otra ruta que no empiece con /es-MX/
    # Ejemplo: si alguien entra a /products, lo manda a /es-MX/products
    location / {
        return 301 /es-MX$request_uri;
    }
}
